AKHQ-92 Delete Topic
polarising-oss/kafkahq pull request #48
Opened 2020-03-04 17:15 UTC by lyudmylatodoriko

- Finished Backend and Frontend implementation for topic delete

2020-03-04 19:20 UTC, goncaloValentim requested changes

2020-03-04 19:20 UTC, goncaloValentim commented on client/src/containers/TopicList/TopicList.jsx
> +    //this.deleteTopic(topic);
Ele faz o delete com esta linha comentada?

2020-03-04 19:20 UTC, goncaloValentim commented on src/main/java/org/kafkahq/rest/TopicResource.java
> +    public List<TopicDTO> deleteTopic(@Body DeleteTopicDTO deleteTopicDTO) throws ExecutionException, InterruptedException {
Falta um log.debug neste método. É importante colocar logs nas classes que mexem com dados (como os services) mas é ainda mais importante nas classes de resource de modo a saber o estado do programa (bastante importante em produção).

2020-03-04 19:20 UTC, goncaloValentim commented on client/src/utils/api.js
> +    console.log('body', body);
Remover console log

2020-03-05 09:39 UTC, lyudmylatodoriko commented on client/src/containers/TopicList/TopicList.jsx
> +    //this.deleteTopic(topic);
Faz sim, essa função é utilizada para chamar o modal de confirmação do delete. Vou retirar esse comment.

2020-03-05 10:49 UTC, goncaloValentim approved these changes

2020-03-05 10:49 UTC, merged